---
apiVersion: v1
kind: Pod
metadata:
  name: recatapppod
  labels:
    app: recatapppod #very imp
spec:
  containers:
  - name: recatappcontainer
    image: dockerpandian/todo-react
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: recatapppodsvc
spec:
  type: LoadBalancer
  selector:
    app: recatapppod  #POD label
  ports:
    - port: 80
      targetPort: 80
